name: jaytap
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #==================== FIREBASE ====================#
  firebase_core: ^3.1.1
  firebase_core_platform_interface: ^6.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^19.4.0

  #==================== STATE MANAGEMENT ====================#
  get: ^4.7.2

  #==================== NETWORK ====================#
  http:
  dio: ^5.3.3
  web_socket_channel: ^3.0.3

  #==================== UI & UX ====================#
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  dotted_border: ^2.1.0
  flutter_iconly: ^1.0.2
  hugeicons: ^0.0.11
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  upgrader: ^10.3.0
  flutter_html: ^3.0.0-beta.2

  #==================== MAPS & LOCATION ====================#
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geolocator_android: ^4.6.1
  permission_handler: ^11.0.1
  panorama: ^0.4.1

  #==================== LOCAL STORAGE ====================#
  get_storage: ^2.1.1

  #==================== UTILITIES ====================#
  kartal: ^3.5.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.2.1
  sms_autofill: ^2.4.1
  motion_sensors: ^0.1.0

  #==================== MEDIA ====================#
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  video_player: ^2.7.2
  chewie: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  motion_sensors: ^0.1.0
  geolocator_android: 4.6.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/category/
    - assets/images/realtor/
    - assets/images/banners/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600